version: "2.22"
services:
  post-crud:
    container_name: post-crud
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  mongodb:
    image: mongo:latest
    container_name: my-mongodb
    ports:
      - "27018:27017"
